# Simple, Stupid implementation of logistic regression
by: Seyed Reza Darijani

In [1]:
import numpy as np

In [2]:
def sigmoid(z):
    """defining sigmoid function for activation function"""
    return (1/(1+np.exp(-z)))

### A very Simple Dataset
(three numbers as inputs and if the sum is >= 9 then output is (1) else output is (0))

In [3]:
#loading first three columns as inputs (5000,3) and transpose it (3,5000)
x = np.loadtxt('train_set.csv', usecols=(0,1,2), delimiter=',').T

#loading fourth column as output (5000,)(1d array) and reshape it (1,5000)(2d array)
y = np.loadtxt('train_set.csv', usecols=(3,), delimiter=',').reshape(1,5000)

print('inputs:\n',x)
print('\noutputs:\n',y)

inputs:
 [[3. 2. 3. ... 4. 3. 1.]
 [3. 2. 3. ... 5. 1. 3.]
 [4. 3. 6. ... 4. 1. 1.]]

outputs:
 [[1. 0. 1. ... 1. 0. 0.]]


In [4]:
#initial weights and bias
w = np.zeros((3,1))
b = 0

print('\ninitial weights:\n',w)
print('\ninitial bias:\n',b)


initial weights:
 [[0.]
 [0.]
 [0.]]

initial bias:
 0


In [5]:
#learning rate
alpha = 0.5

# 3968 iteration for _gradient descent_ convex optimization technique
for i in range(3968):
    
    #forward propagation
    z = np.matmul(w.T, x)+b
    a = sigmoid(z)
    
    #backward propagation
    dz = a-y
    dw = (x * dz).sum(axis=1, keepdims=True) / 5000
    db = dz.sum() / 5000
    tempw = w - alpha*dw
    tempb = b - alpha*db
    w = tempw
    b = tempb
    
    
#print results   
print('after training weights:\n',w)
print('\nafter training bias:\n',b)

after training weights:
 [[2.34308783]
 [2.32703968]
 [2.32214983]]

after training bias:
 -19.612496736794892


>Feel free to reRUN the cell above multiple times or with different iteration number

In [6]:
print('\nsum of difference between all labeled outputs and our model outputs:\n',dz.sum())


sum of difference between all labeled outputs and our model outputs:
 19.643407287296405


#### Note:
the differnce between our model 5000 outputs(Matrix a(1,5000)) and real outputs(Matrix y(1,5000)) smoothly go near zero.  
actually with more iteration, it will be more near zero.  
>Logestic regression like the perceptron is a linear classifier, therefore it will never get to the state with all the input vectors classified correctly if the training set  is not linearly separable.  
https://en.wikipedia.org/wiki/Perceptron#Convergence

>__but__ _our training set is linearly separable_.(three numbers as inputs and if the sum is >= 9 then output is (1) else output is (0))

---

# using scikit-learn package

scikit-learn results are in accordance with our model with __learning rate (alpha=0.5)__ and __3968 iteration__ approximately

In [7]:
from sklearn.linear_model import LogisticRegression

#loading fourth column as output (5000,)(1d array)
y = np.loadtxt('train_set.csv', usecols=(3,), delimiter=',')

model = LogisticRegression(solver='liblinear', random_state=0)
model.fit(x.T, y)
print(model.intercept_)
print(model.coef_)


[-19.61286299]
[[2.34308311 2.32708229 2.32219568]]


In [8]:
model.predict_proba(np.loadtxt('test_set.csv', usecols=(0,1,2), delimiter=','))

array([[2.02764183e-01, 7.97235817e-01],
       [2.26624652e-05, 9.99977338e-01],
       [2.00973495e-01, 7.99026505e-01],
       ...,
       [2.28336394e-06, 9.99997717e-01],
       [2.29938484e-04, 9.99770062e-01],
       [2.45979091e-02, 9.75402091e-01]])